<?php
/**
*	generates the manual/$lang/manual.xml file for a specific language
*	from the manual/manual.xml.in template file
*/

$template = 'manual/manual.xml.in';

if (!file_exists($template)) {
	die("\r\nRun the script from the base php-gtk-doc directory\r\n");
}
if ($GLOBALS['argc'] < 2 || strlen($GLOBALS['argv'][1]) != 2) {
	die("\r\nError: Pass the desired language as only parameter\r\n");
}
$lang = $GLOBALS['argv'][1];
if (!is_dir('manual/' . $lang)) {
	die("\r\nThere is no directory for language $lang\r\n");
}

$outputfile = 'manual/' . $lang . '/manual.xml';

$hdl = fopen($outputfile, "w+");

fwrite($hdl,
	str_replace( '@PHP_GTK2_DOC_BUILD_DATE@', date('r'), 
	str_replace( '@LANG@', $lang,
	str_replace( '<!DOCTYPE', "<!-- DO NOT EDIT THIS FILE! IT IS GENERATED AUTOMATICALLY BY gen_manualxml.php -->\r\n<!DOCTYPE", 
		file_get_contents($template)
	)))
);

fclose($hdl);
?>